#![cfg(feature = "shacl")]

const SHAPES: &str = include_str!("../shapes/aegis-ontology.shapes.ttl");
const PREFIXES: &str = r#"
@prefix a: <http://aegis.gastown.local/ontology/> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
"#;
const RULE: &str = r#"
<urn:example:reaction> a a:Reaction ;
    rdfs:label "example-rule" ;
    a:triggerKind "schedule" ; a:schedule "PT5M" ;
    a:condition "SELECT ?focus WHERE { ?focus a ?type }" ;
    a:severity "warning" ; a:action "alert", "bead" ; a:owner "example" .
"#;
const FIRING: &str = r#"
<urn:example:firing> a a:ReactionFiring ;
    a:firedBy <urn:example:reaction> ; a:focus <urn:example:item> ;
    a:startedAt "2026-09-26T05:00:00Z"^^xsd:dateTime .
"#;

fn conforms(data: &str) -> bool {
    quipu::validate_shapes(SHAPES, &format!("{PREFIXES}{data}"))
        .unwrap()
        .conforms
}

#[test]
fn chaski_emitter_payload_matches_the_governed_contract() {
    // Generated by scbrown/chaski graph_sink.py at a8e3f8b4:
    // QuipuFiringSink.reaction_turtle() + firing_turtle().
    assert!(conforms(include_str!(
        "../test-fixtures/chaski-emitter.ttl"
    )));
}

#[test]
fn schedule_and_event_rules_allow_multiple_actions_and_optional_enabled() {
    assert!(conforms(RULE));
    let event = RULE.replace("\"schedule\"", "\"event\"").replace(
        "a:schedule \"PT5M\"",
        "a:eventTypes \"entity.updated,edge.added\"",
    );
    assert!(conforms(&event));
    for enabled in ["true", "false"] {
        assert!(conforms(&format!(
            "{event}<urn:example:reaction> a:enabled {enabled} ."
        )));
    }
}

#[test]
fn reaction_requires_its_identity_and_evaluation_fields() {
    for field in [
        "rdfs:label \"example-rule\" ;",
        "a:triggerKind \"schedule\" ;",
        "a:condition \"SELECT ?focus WHERE { ?focus a ?type }\" ;",
        "a:severity \"warning\" ;",
        "a:action \"alert\", \"bead\" ;",
        "a:owner \"example\"",
    ] {
        assert!(!conforms(&RULE.replace(field, "")), "{field}");
    }
}

#[test]
fn reaction_rejects_unknown_enums_wrong_types_and_singleton_conflicts() {
    for (from, to) in [
        ("\"schedule\"", "\"poll\""),
        ("\"warning\"", "\"urgent\""),
        ("\"alert\", \"bead\"", "\"shell\""),
        ("\"PT5M\"", "5"),
        ("\"example\"", "<urn:example:owner>"),
        ("\"schedule\"", "\"schedule\", \"event\""),
    ] {
        assert!(!conforms(&RULE.replace(from, to)), "{from} -> {to}");
    }
    assert!(!conforms(&format!(
        "{RULE}<urn:example:reaction> a:enabled \"false\" ."
    )));
}

#[test]
fn firing_accepts_active_resolved_and_event_identified_records() {
    let data = format!("{RULE}{FIRING}");
    assert!(conforms(&data));
    assert!(conforms(&format!(
        "{data}<urn:example:firing> a:eventId \"stable-event\" ; \
         a:resolvedAt \"2026-09-26T05:01:00Z\"^^xsd:dateTime ."
    )));
}

#[test]
fn firing_requires_typed_reaction_iri_focus_and_start_instant() {
    for field in [
        "a:firedBy <urn:example:reaction> ;",
        "a:focus <urn:example:item> ;",
        "a:startedAt \"2026-09-26T05:00:00Z\"^^xsd:dateTime",
    ] {
        assert!(!conforms(&format!("{RULE}{}", FIRING.replace(field, ""))));
    }
    for (from, to) in [
        (
            "a:firedBy <urn:example:reaction>",
            "a:firedBy <urn:example:untyped>",
        ),
        ("a:focus <urn:example:item>", "a:focus \"item\""),
        ("a:focus <urn:example:item>", "a:focus _:item"),
        (
            "\"2026-09-26T05:00:00Z\"^^xsd:dateTime",
            "\"2026-09-26T05:00:00Z\"",
        ),
    ] {
        assert!(!conforms(&format!("{RULE}{}", FIRING.replace(from, to))));
    }
}

#[test]
fn firing_rejects_conflicting_identity_and_resolution_fields() {
    for extra in [
        "a:eventId 42",
        "a:eventId <urn:example:event>",
        "a:eventId \"one\", \"two\"",
        "a:resolvedAt \"not-a-date\"",
        "a:resolvedAt \"2026-09-26T05:01:00Z\"^^xsd:dateTime, \"2026-09-26T05:02:00Z\"^^xsd:dateTime",
        "a:focus <urn:example:other>",
        "a:startedAt \"2026-09-26T05:02:00Z\"^^xsd:dateTime",
    ] {
        assert!(
            !conforms(&format!("{RULE}{FIRING}<urn:example:firing> {extra} .")),
            "{extra}"
        );
    }
}
