//! Episode ingestion — structured write path for agent-extracted knowledge.
//!
//! Episodes are the primary unit of knowledge ingestion from Gas Town agents.
//! An episode contains a set of nodes (entities) and edges (relationships)
//! extracted from operational events, bead work, or infrastructure observations.
//!
//! This module converts the structured JSON format used by Graphiti/Gas Town
//! into RDF Turtle and writes it through the existing `ingest_rdf` pipeline.

use serde::Deserialize;

use crate::error::{Error, Result};
use crate::rdf::ingest_rdf;
#[cfg(feature = "shacl")]
use crate::shacl;
use crate::store::Store;

const BASE_NS: &str = "http://aegis.gastown.local/ontology/";

/// An episode — a unit of knowledge to ingest.
#[derive(Debug, Deserialize)]
pub struct Episode {
    pub name: String,
    #[serde(default)]
    pub episode_body: Option<String>,
    #[serde(default)]
    pub source: Option<String>,
    #[serde(default)]
    pub group_id: Option<String>,
    #[serde(default)]
    pub nodes: Vec<Node>,
    #[serde(default)]
    pub edges: Vec<Edge>,
    /// Optional SHACL shapes (Turtle) to validate generated triples against.
    #[serde(default)]
    pub shapes: Option<String>,
}

/// A node (entity) extracted from an episode.
#[derive(Debug, Deserialize)]
pub struct Node {
    pub name: String,
    #[serde(rename = "type", default)]
    pub node_type: Option<String>,
    #[serde(default)]
    pub description: Option<String>,
    #[serde(default)]
    pub properties: Option<serde_json::Map<String, serde_json::Value>>,
}

/// An edge (relationship) between two nodes.
#[derive(Debug, Deserialize)]
pub struct Edge {
    pub source: String,
    pub target: String,
    pub relation: String,
}

/// Ingest an episode into the store.
///
/// Converts nodes and edges to Turtle and writes via `ingest_rdf`.
/// Returns `(tx_id, triple_count)`.
pub fn ingest_episode(
    store: &mut Store,
    episode: &Episode,
    timestamp: &str,
) -> Result<(i64, usize)> {
    let turtle = episode_to_turtle(episode);

    // SHACL validation gate: if shapes provided, validate before writing.
    #[cfg(feature = "shacl")]
    if let Some(shapes) = &episode.shapes {
        let feedback = shacl::validate_shapes(shapes, &turtle)?;
        if !feedback.conforms {
            let messages: Vec<String> = feedback
                .results
                .iter()
                .map(|r| {
                    format!(
                        "{}: {} ({})",
                        r.severity,
                        r.message.as_deref().unwrap_or("no message"),
                        r.focus_node
                    )
                })
                .collect();
            return Err(Error::ValidationFailed {
                violations: feedback.violations,
                messages,
            });
        }
    }

    let actor = episode.source.as_deref();
    let source_str = format!("episode:{}", episode.name);

    ingest_rdf(
        store,
        turtle.as_bytes(),
        oxrdfio::RdfFormat::Turtle,
        None,
        timestamp,
        actor,
        Some(&source_str),
    )
}

/// Ingest multiple episodes in sequence, each as its own transaction.
/// Stops on first error.
pub fn ingest_batch(
    store: &mut Store,
    episodes: &[Episode],
    timestamps: &[&str],
) -> Result<Vec<(i64, usize)>> {
    let mut results = Vec::with_capacity(episodes.len());
    for (i, episode) in episodes.iter().enumerate() {
        let ts = timestamps.get(i).copied().unwrap_or("1970-01-01T00:00:00Z");
        results.push(ingest_episode(store, episode, ts)?);
    }
    Ok(results)
}

/// Query all entities generated by a specific episode via prov:wasGeneratedBy.
pub fn episode_provenance(
    store: &Store,
    episode_name: &str,
) -> Result<Vec<(String, Vec<crate::types::Fact>)>> {
    let ep_local = sanitize_iri_local(episode_name);
    let ep_iri = format!("{BASE_NS}episode_{ep_local}");
    let query = format!(
        "SELECT DISTINCT ?s WHERE {{ ?s <http://www.w3.org/ns/prov#wasGeneratedBy> <{ep_iri}> }}"
    );
    let result = crate::sparql::query(store, &query)?;

    let mut entities = Vec::new();
    for row in result.rows() {
        if let Some(crate::types::Value::Ref(id)) = row.get("s") {
            let iri = store.resolve(*id)?;
            let facts = store.entity_facts(*id)?;
            entities.push((iri, facts));
        }
    }
    Ok(entities)
}

// ── Turtle generation ──────────────────────────────────────────

fn episode_to_turtle(episode: &Episode) -> String {
    let mut ttl = String::new();

    // Prefixes.
    ttl.push_str(&format!("@prefix aegis: <{BASE_NS}> .\n"));
    ttl.push_str("@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .\n");
    ttl.push_str("@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .\n");
    ttl.push_str("@prefix prov: <http://www.w3.org/ns/prov#> .\n");
    ttl.push_str("@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n\n");

    let ep_local = sanitize_iri_local(&episode.name);

    // Episode provenance entity.
    ttl.push_str(&format!("aegis:episode_{ep_local} a prov:Activity ;\n"));
    ttl.push_str(&format!(
        "    rdfs:label \"{}\"",
        escape_turtle(&episode.name)
    ));
    if let Some(body) = &episode.episode_body {
        ttl.push_str(&format!(" ;\n    rdfs:comment \"{}\"", escape_turtle(body)));
    }
    if let Some(source) = &episode.source {
        ttl.push_str(&format!(
            " ;\n    prov:wasAssociatedWith \"{}\"",
            escape_turtle(source)
        ));
    }
    if let Some(gid) = &episode.group_id {
        ttl.push_str(&format!(" ;\n    aegis:groupId \"{}\"", escape_turtle(gid)));
    }
    ttl.push_str(" .\n\n");

    // Nodes.
    for node in &episode.nodes {
        let local = sanitize_iri_local(&node.name);
        ttl.push_str(&format!("aegis:{local}"));

        if let Some(ntype) = &node.node_type {
            let type_local = sanitize_iri_local(ntype);
            ttl.push_str(&format!(" a aegis:{type_local}"));
        }

        ttl.push_str(&format!(
            " ;\n    rdfs:label \"{}\"",
            escape_turtle(&node.name)
        ));

        if let Some(desc) = &node.description {
            ttl.push_str(&format!(" ;\n    rdfs:comment \"{}\"", escape_turtle(desc)));
        }

        // Link to episode provenance.
        ttl.push_str(&format!(
            " ;\n    prov:wasGeneratedBy aegis:episode_{ep_local}"
        ));

        // Optional properties as typed literals.
        if let Some(props) = &node.properties {
            for (key, val) in props {
                let pred = sanitize_iri_local(key);
                match val {
                    serde_json::Value::String(s) => {
                        ttl.push_str(&format!(" ;\n    aegis:{pred} \"{}\"", escape_turtle(s)));
                    }
                    serde_json::Value::Number(n) => {
                        if let Some(i) = n.as_i64() {
                            ttl.push_str(&format!(" ;\n    aegis:{pred} \"{i}\"^^xsd:integer"));
                        } else if let Some(f) = n.as_f64() {
                            ttl.push_str(&format!(" ;\n    aegis:{pred} \"{f}\"^^xsd:double"));
                        }
                    }
                    serde_json::Value::Bool(b) => {
                        ttl.push_str(&format!(" ;\n    aegis:{pred} \"{b}\"^^xsd:boolean"));
                    }
                    _ => {} // skip arrays/objects/null
                }
            }
        }

        ttl.push_str(" .\n\n");
    }

    // Edges.
    for edge in &episode.edges {
        let src = sanitize_iri_local(&edge.source);
        let tgt = sanitize_iri_local(&edge.target);
        let rel = sanitize_iri_local(&edge.relation);
        ttl.push_str(&format!("aegis:{src} aegis:{rel} aegis:{tgt} .\n"));
    }

    ttl
}

/// Sanitize a name into a valid IRI local name.
fn sanitize_iri_local(name: &str) -> String {
    name.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '-' || c == '_' || c == '.' {
                c
            } else {
                '_'
            }
        })
        .collect()
}

/// Escape special characters for Turtle string literals.
fn escape_turtle(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
}

#[cfg(test)]
mod tests;
