#!/usr/bin/env bash
# export-datalinks.sh — bake a Datalinks graph into static JSON for GitHub Pages.
#
# The published demo has no Quipu behind it, so the payload the UI would fetch
# from POST /graph and POST /query is captured here instead. It goes through a
# REAL server rather than re-deriving the projection in a script: graph_view.rs
# does the predicate filtering, degree ranking and index-addressing, and a
# hand-rolled copy would drift from what the served UI actually shows.
#
# Usage:
#   scripts/export-datalinks.sh [<graph.ttl>] [<out.json>]
#
# Defaults to the Thinker datalinks graph in the sibling NeuralAmplifier
# checkout, which owns and regenerates it. Commit the output: the Pages build
# must not need Rust.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

GRAPH="${1:-../NeuralAmplifier/datalinks/thinker/alphax.ttl}"
OUT="${2:-docs/book/src/datalinks/graph.json}"
PORT="${PORT:-3931}"
DB="$(mktemp -u /tmp/quipu-export-XXXXXX.db)"
SMAC_NS="http://neuralamplifier.local/ontology/smac"

if [ ! -f "$GRAPH" ]; then
    echo "error: graph not found: $GRAPH" >&2
    echo "  Pass a path, or check out scbrown/NeuralAmplifier beside this repo." >&2
    exit 2
fi

echo "building quipu + quipu-server..." >&2
cargo build --quiet --bin quipu --features shacl
cargo build --quiet --bin quipu-server --features shacl,onnx

echo "loading $GRAPH..." >&2
./target/debug/quipu knot "$GRAPH" --db "$DB" >&2

./target/debug/quipu-server --db "$DB" --bind "127.0.0.1:$PORT" >/dev/null 2>&1 &
SERVER_PID=$!
trap 'kill "$SERVER_PID" 2>/dev/null || true; rm -f "$DB"' EXIT

for _ in $(seq 1 40); do
    if curl -sf "http://127.0.0.1:$PORT/health" >/dev/null 2>&1; then break; fi
    sleep 0.25
done
curl -sf "http://127.0.0.1:$PORT/health" >/dev/null || { echo "server did not start" >&2; exit 1; }

api() {
    curl -sf "http://127.0.0.1:$PORT/$1" \
        -X POST -H 'Content-Type: application/json' -d "$2"
}

# The structure, and the per-entity enrichment the entry panel reads. Kept as
# two calls because that is exactly what the live UI does.
# Via temp FILES, not environment variables: the graph payload alone is well
# past the environment size limit and exec fails with "Argument list too long".
TMP_GRAPH="$(mktemp)"
TMP_ENRICH="$(mktemp)"
trap 'kill "$SERVER_PID" 2>/dev/null || true; rm -f "$DB" "$TMP_GRAPH" "$TMP_ENRICH"' EXIT

api graph '{"limit":2000}' > "$TMP_GRAPH"
ENRICH_PREDS='effectText ruleTier abbrev aiWeightGrowth aiWeightTech aiWeightWealth aiWeightPower'
VALUES=""
for p in $ENRICH_PREDS; do VALUES="$VALUES <$SMAC_NS/$p>"; done
api query "$(printf '{"query":"SELECT ?s ?p ?o WHERE { ?s ?p ?o . VALUES ?p {%s} }"}' "$VALUES")" \
    > "$TMP_ENRICH"

mkdir -p "$(dirname "$OUT")"
SOURCE="$GRAPH" python3 - "$OUT" "$TMP_GRAPH" "$TMP_ENRICH" <<'PY'
import json, os, sys

with open(sys.argv[2], encoding="utf-8") as fh:
    graph = json.load(fh)
with open(sys.argv[3], encoding="utf-8") as fh:
    rows = json.load(fh).get("rows", [])

# Fold the (s, p, o) rows into per-IRI dicts keyed by the predicate's local
# name, which is the shape ui/datalinks.js setEnrichment() expects.
enrich = {}
for row in rows:
    subject, pred, obj = row["s"], row["p"], row["o"]
    enrich.setdefault(subject, {})[str(pred).rsplit("/", 1)[-1]] = obj

out = {
    "_source": os.environ["SOURCE"],
    "_note": "Generated by scripts/export-datalinks.sh — regenerate, do not hand-edit.",
    "graph": graph,
    "enrichment": enrich,
}
with open(sys.argv[1], "w", encoding="utf-8") as fh:
    json.dump(out, fh, separators=(",", ":"), sort_keys=True)
    fh.write("\n")

stats = graph.get("stats", {})
print(
    f"wrote {sys.argv[1]}: {stats.get('nodes', '?')} nodes, "
    f"{stats.get('edges', '?')} edges, {len(enrich)} enriched",
    file=sys.stderr,
)
PY
