#!/usr/bin/env python3
"""Performance gate for the string-FILTER query shapes agents write (aegis-66ny04).

quipu#433 (aegis-tl2q4j) pushes CONTAINS / STRSTARTS / STRENDS / REGEX filters
into the SQL scan, which took agent-written string filters from timeouts to
well under a second on the production store. Nothing in CI exercised those
shapes, so a change that undid the narrowing would have passed every check.

Three subcommands:

  generate  write a deterministic production-shaped fixture as N-Triples, one
            file per graph, plus a manifest (counts and sha256 per file).
            Neutral example.org IRIs only: no internal names enter the repo.
  gate      run every query class against a server loaded with that fixture,
            each one TWICE: as written (pushed) and as FILTER((X) || false),
            which no pushdown touches (defeated). It fails when
              - the two forms return different rows (pushdown changed an answer),
              - defeated/pushed falls below the class's min ratio (the narrowing
                stopped working, measured in-run so runner speed cancels out),
              - pushed p95 exceeds the class's ceiling, absolute or relative to
                the in-run C0 control.
            A known-slow class is reported, and fails only on its timeout.
  smoke     run the pushed form of every class against a served store and
            report p50/p95 per class. No defeated runs: those are full scans,
            and this mode points at production after a deploy.

The defeated form is the positive control, and it runs on every PR: if the
planner ever learns to see through `|| false`, the ratio collapses and the gate
fails loudly instead of going vacuous.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import random
import statistics
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

NS = "http://example.org/perf/"
RDF_TYPE = "http://www.w3.org/1999/02/22-rdf-syntax-ns#type"
RDFS_LABEL = "http://www.w3.org/2000/01/rdf-schema#label"
RDFS_COMMENT = "http://www.w3.org/2000/01/rdf-schema#comment"
GRAPH_NS = "urn:perf:graph:"
ROOT_GRAPH = "urn:quipu:graph:root"
TIMESTAMP = "2026-10-08T00:00:00Z"

# Bump when the generated bytes change, so a CI cache keyed on it is replaced.
GENERATOR_VERSION = 1

PREFIXES = (
    f"PREFIX ex: <{NS}> "
    "PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> "
)

# Rare needles, each planted at a known rate so a query's row count is stable
# and small, which is the shape where narrowing pays.
NEEDLE_RATE = {
    "drain": 0.002,  # comments in the knowledge graph (Q2)
    "index.example": 0.0005,  # labels (Q3)
    "case-9ka": 0.0005,  # labels (Q3)
    "Dolt": 0.002,  # comments (Q5)
    "quipu": 0.001,  # labels (Q8)
}
# Subjects whose IRI carries this text (Q4).
SUBJECT_NEEDLE = "case-lmi"
SUBJECT_NEEDLE_COUNT = 12


def words(rng: random.Random, vocab: list[str], n: int) -> str:
    return " ".join(rng.choice(vocab) for _ in range(n))


def make_vocab(rng: random.Random, size: int) -> list[str]:
    letters = "abcdefghiklmnoprstuvwy"
    out = set()
    while len(out) < size:
        out.add("".join(rng.choice(letters) for _ in range(rng.randint(3, 9))))
    # The needles must never occur by accident.
    return sorted(w for w in out if not any(n.lower() in w for n in NEEDLE_RATE))


def lit(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def plan_graphs(graphs: int) -> list[str]:
    names = ["knowledge", "seeds-alpha", "seeds-beta", "seeds-gamma"]
    names += [f"lane-{i:02d}" for i in range(graphs - len(names))]
    return names


def generate(out: Path, entities: int, seed: int, graphs: int) -> dict:
    """Write the fixture and return its manifest."""
    rng = random.Random(seed)
    vocab = make_vocab(rng, 4000)
    types = ["Directive", "FailureMode", "WorkItem"] + [f"Kind{i:03d}" for i in range(117)]
    # Zipf-ish: a few types dominate, as on a real board.
    type_weights = [1.0 / (i + 1) for i in range(len(types))]
    preds = ["status", "statusCode", "workStatus"] + [f"p{i:03d}" for i in range(197)]
    pred_weights = [1.0 / math.sqrt(i + 1) for i in range(len(preds))]
    graph_names = plan_graphs(graphs)

    out.mkdir(parents=True, exist_ok=True)
    handles = {"root": open(out / "root.nt", "w", encoding="utf-8")}
    for g in graph_names:
        handles[g] = open(out / f"{g}.nt", "w", encoding="utf-8")

    needle_subjects = set(rng.sample(range(entities), SUBJECT_NEEDLE_COUNT))
    try:
        for i in range(entities):
            # 70% of entities live in the default graph, like episodes do.
            if rng.random() < 0.7:
                gkey = "root"
            elif rng.random() < 0.3:
                gkey = "knowledge"
            else:
                gkey = rng.choice(graph_names)
            fh = handles[gkey]
            local = f"e{i:07d}"
            if i in needle_subjects:
                local = f"{SUBJECT_NEEDLE}-{i}"
            s = f"<{NS}{local}>"
            t = rng.choices(types, type_weights)[0]
            fh.write(f"{s} <{RDF_TYPE}> <{NS}{t}> .\n")

            label = words(rng, vocab, rng.randint(2, 4))
            for needle in ("index.example", "case-9ka", "quipu"):
                if rng.random() < NEEDLE_RATE[needle]:
                    label += f" {needle}"
            fh.write(f"{s} <{RDFS_LABEL}> {lit(label)} .\n")

            comment = words(rng, vocab, rng.randint(6, 16))
            for needle in ("drain", "Dolt"):
                if rng.random() < NEEDLE_RATE[needle]:
                    comment += f" {needle}"
            fh.write(f"{s} <{RDFS_COMMENT}> {lit(comment)} .\n")

            for _ in range(rng.randint(5, 17)):
                p = rng.choices(preds, pred_weights)[0]
                roll = rng.random()
                if roll < 0.4:
                    o = f"<{NS}e{rng.randrange(entities):07d}>"
                elif roll < 0.6:
                    o = f'"{rng.randint(0, 100000)}"^^<http://www.w3.org/2001/XMLSchema#integer>'
                else:
                    o = lit(words(rng, vocab, rng.randint(1, 5)))
                fh.write(f"{s} <{NS}{p}> {o} .\n")
    finally:
        for fh in handles.values():
            fh.close()

    files = []
    for key in ["root", *graph_names]:
        path = out / f"{key}.nt"
        data = path.read_bytes()
        files.append(
            {
                "file": path.name,
                "graph": ROOT_GRAPH if key == "root" else GRAPH_NS + key,
                "triples": data.count(b"\n"),
                "sha256": hashlib.sha256(data).hexdigest(),
            }
        )
    manifest = {
        "generator_version": GENERATOR_VERSION,
        "entities": entities,
        "seed": seed,
        "graphs": graphs,
        "timestamp": TIMESTAMP,
        "triples": sum(f["triples"] for f in files),
        "files": files,
    }
    (out / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    return manifest


# Each class is a template with `{f}` where the FILTER expression goes, so the
# defeated form wraps exactly that expression and nothing else. `limit` is
# appended for the timed runs; the differential runs without it, because two
# scans may legitimately return different first-N rows.
CLASSES: dict[str, dict] = {
    "C0_control_exact": {
        "q": "SELECT (COUNT(?s) AS ?n) WHERE { ?s a ex:Directive }",
        "control": True,
    },
    "Q1_status_pred": {
        "q": "SELECT (COUNT(DISTINCT ?s) AS ?n) WHERE { ?s a ex:WorkItem ; ?sp ?o . "
        'FILTER({f}) }',
        "f": 'CONTAINS(LCASE(STR(?sp)), "status")',
    },
    "Q2_graph_literal_substr": {
        "q": f"SELECT ?s WHERE {{ GRAPH <{GRAPH_NS}knowledge> {{ ?s ?p ?o . FILTER({{f}}) }} }}",
        "f": 'isLiteral(?o) && CONTAINS(LCASE(STR(?o)), "drain")',
        "limit": 50,
    },
    "Q3_label_regex": {
        "q": "SELECT ?s ?l WHERE { ?s rdfs:label ?l . FILTER({f}) }",
        "f": 'REGEX(STR(?l), "index\\\\.example|case-9ka")',
    },
    "Q4_subject_contains": {
        "q": "SELECT ?s ?p ?o WHERE { ?s ?p ?o . FILTER({f}) }",
        "f": f'CONTAINS(STR(?s), "{SUBJECT_NEEDLE}")',
    },
    "Q5_comment_contains": {
        "q": "SELECT ?s WHERE { ?s rdfs:comment ?o . FILTER({f}) }",
        "f": 'CONTAINS(STR(?o), "Dolt")',
        "limit": 50,
    },
    "Q6_type_regex_count": {
        "q": "SELECT ?t (COUNT(?s) AS ?n) WHERE { ?s a ?t . FILTER({f}) } GROUP BY ?t",
        "f": 'REGEX(STR(?t), "Directive|FailureMode")',
    },
    "Q7_graph_var_contains": {
        "q": "SELECT ?g (COUNT(*) AS ?n) WHERE { GRAPH ?g { ?s a ?t } FILTER({f}) } GROUP BY ?g",
        "f": 'CONTAINS(STR(?g), "seeds")',
        "known_slow": "aegis-nmouik",
    },
    "Q8_label_lcase_contains": {
        "q": "SELECT ?s ?l WHERE { ?s rdfs:label ?l . FILTER({f}) }",
        "f": 'CONTAINS(LCASE(?l), "quipu")',
        "limit": 100,
    },
    "Q9_subject_strstarts": {
        "q": "SELECT ?s ?l WHERE { ?s rdfs:label ?l . FILTER({f}) }",
        "f": f'STRSTARTS(STR(?s), "{NS}{SUBJECT_NEEDLE}")',
    },
}


def render(cls: dict, defeated: bool, limit: bool) -> str:
    q = cls["q"]
    if "f" in cls:
        f = f"({cls['f']}) || false" if defeated else cls["f"]
        q = q.replace("{f}", f)
    if limit and cls.get("limit"):
        q += f" LIMIT {cls['limit']}"
    return PREFIXES + q


def run_query(url: str, sparql: str, timeout: float) -> tuple[float, str, list | None]:
    """Return (seconds, status, rows). status is "ok", an HTTP code, or an error name."""
    body = json.dumps({"query": sparql}).encode()
    req = urllib.request.Request(
        url.rstrip("/") + "/query",
        body,
        {"Content-Type": "application/json", "X-Quipu-Client": "perf-gate"},
    )
    started = time.monotonic()
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            data = json.load(resp)
        rows = data.get("results", data.get("rows")) if isinstance(data, dict) else data
        status = "ok" if valid_rows(rows) and not (isinstance(data, dict) and "error" in data) else "malformed"
    except urllib.error.HTTPError as e:
        status, rows = str(e.code), None
    except Exception as e:  # noqa: BLE001 - a timeout is a result here
        status, rows = type(e).__name__, None
    return time.monotonic() - started, status, rows


def valid_rows(rows: object) -> bool:
    return isinstance(rows, list) and all(isinstance(row, dict) for row in rows)


def canon(rows: list) -> list[str]:
    return sorted(json.dumps(r, sort_keys=True) for r in rows)


def pctl(values: list[float], pct: float) -> float:
    ordered = sorted(values)
    return ordered[max(0, math.ceil(pct * len(ordered)) - 1)]


def measure(url: str, name: str, cls: dict, reps: int, timeout: float, defeated: bool) -> dict:
    sparql = render(cls, defeated, limit=True)
    times, statuses, rows = [], [], None
    run_query(url, sparql, timeout)  # warm the page cache and the plan cache
    for _ in range(reps):
        t, status, r = run_query(url, sparql, timeout)
        if status == "ok" and not valid_rows(r):
            status = "malformed"
        times.append(t)
        statuses.append(status)
        rows = r if status == "ok" else rows
    return {
        "p50_ms": round(statistics.median(times) * 1000, 2),
        "p95_ms": round(pctl(times, 0.95) * 1000, 2),
        "errors": sum(1 for s in statuses if s != "ok"),
        "statuses": sorted(set(statuses)),
        "rows": None if rows is None else len(rows),
    }


def gate(url: str, budget: dict, reps: int, timeout: float, only: list[str] | None) -> tuple[dict, list[str]]:
    report: dict = {"url": url, "reps": reps, "classes": {}}
    failures: list[str] = []
    control = measure(url, "C0_control_exact", CLASSES["C0_control_exact"], reps, timeout, False)
    report["classes"]["C0_control_exact"] = {"pushed": control}
    c0 = max(control["p50_ms"], 1.0)
    if control["errors"] or not control["rows"]:
        failures.append(f"C0_control_exact: control failed {control}")
    for name, cls in CLASSES.items():
        if cls.get("control") or (only and name not in only):
            continue
        lim = budget["classes"][name]
        entry: dict = {"pushed": measure(url, name, cls, reps, timeout, False)}
        report["classes"][name] = entry
        pushed = entry["pushed"]
        if cls.get("known_slow"):
            entry["known_slow"] = cls["known_slow"]
            if pushed["errors"]:
                failures.append(f"{name}: known-slow class errored {pushed['statuses']}")
            continue
        # Differential: the narrowed answer must equal the un-narrowed answer.
        _, s1, a = run_query(url, render(cls, False, limit=False), timeout)
        _, s2, b = run_query(url, render(cls, True, limit=False), timeout)
        if s1 != "ok" or s2 != "ok" or not valid_rows(a) or not valid_rows(b):
            failures.append(f"{name}: differential could not run ({s1}, {s2})")
        elif not a:
            failures.append(f"{name}: control: the query matched no rows, so it proves nothing")
        elif canon(a) != canon(b):
            failures.append(f"{name}: pushdown changed the answer ({len(a)} vs {len(b)} rows)")
        entry["differential_rows"] = len(a) if valid_rows(a) else None

        entry["defeated"] = measure(url, name, cls, max(3, reps // 2), timeout, True)
        entry["rel_c0"] = round(pushed["p95_ms"] / c0, 2)
        defeated = entry["defeated"]
        entry["ratio"] = None
        if defeated["errors"] or not defeated["rows"]:
            failures.append(f"{name}: defeated form failed {defeated['statuses']} (rows={defeated['rows']})")
        if pushed["errors"]:
            failures.append(f"{name}: pushed form errored {pushed['statuses']}")
        # Error durations are not query timings: a timeout must never inflate
        # the numerator into evidence that narrowing works.
        if not defeated["errors"] and defeated["rows"] and not pushed["errors"] and pushed["rows"]:
            ratio = defeated["p50_ms"] / max(pushed["p50_ms"], 0.1)
            entry["ratio"] = round(ratio, 2)
            if ratio < lim["min_ratio"]:
                failures.append(
                    f"{name}: narrowing not effective: defeated/pushed {ratio:.1f}x < {lim['min_ratio']}x"
                )
        if pushed["p95_ms"] > lim["max_p95_ms"]:
            failures.append(f"{name}: p95 {pushed['p95_ms']}ms > {lim['max_p95_ms']}ms")
        if entry["rel_c0"] > lim["max_rel_c0"]:
            failures.append(f"{name}: p95 is {entry['rel_c0']}x C0 > {lim['max_rel_c0']}x")
    report["failures"] = failures
    return report, failures


def smoke(url: str, reps: int, timeout: float) -> dict:
    out = {"url": url, "reps": reps, "classes": {}}
    for name, cls in CLASSES.items():
        out["classes"][name] = measure(url, name, cls, reps, timeout, False)
    return out


def load(fixture: Path, db: Path, quipu: str) -> None:
    """Load the fixture into `db` with declared ingests, refusing on any shortfall.

    `quipu ingest` refuses ROOT by design (a declaration describes one window,
    and ROOT is the whole store), so the default-graph file is ingested into a
    named graph of a scratch store and then imported into ROOT with
    `quipu graph import ... --as <root>`.
    """
    import subprocess

    manifest = json.loads((fixture / "manifest.json").read_text())

    def run(*argv: str) -> None:
        proc = subprocess.run([quipu, *argv], capture_output=True, text=True)
        if proc.returncode != 0:
            raise SystemExit(f"load failed: quipu {' '.join(argv)}\n{proc.stdout}{proc.stderr}")

    for f in manifest["files"]:
        root = f["graph"] == ROOT_GRAPH
        target = db.with_name(db.name + ".rootsrc") if root else db
        graph = GRAPH_NS + "rootsrc" if root else f["graph"]
        run(
            "ingest", str(fixture / f["file"]),
            "--graph", graph,
            "--timestamp", manifest["timestamp"],
            "--declare-count", str(f["triples"]),
            "--declare-sha256", f["sha256"],
            "--db", str(target),
        )
        if root:
            run("graph", "import", str(target), "--as", ROOT_GRAPH, "--db", str(db))
            for suffix in ("", "-wal", "-shm"):
                Path(str(target) + suffix).unlink(missing_ok=True)


def self_test() -> None:
    """Offline checks: determinism, budget coverage, and the defeated form."""
    import tempfile

    with tempfile.TemporaryDirectory() as tmp:
        a = generate(Path(tmp) / "a", 2000, 66, 26)
        b = generate(Path(tmp) / "b", 2000, 66, 26)
        assert a["files"] == b["files"], "generator is not deterministic"
        c = generate(Path(tmp) / "c", 2000, 67, 26)
        assert a["files"] != c["files"], "control: the seed changes the bytes"
        assert any(f["graph"] == ROOT_GRAPH for f in a["files"]), "no default-graph file"
        assert any(f["graph"] == GRAPH_NS + "knowledge" for f in a["files"]), "no knowledge graph"
        text = (Path(tmp) / "a" / "root.nt").read_text()
        assert "example.org" in text and ".svc" not in text and ".lan" not in text

    budget = json.loads((Path(__file__).resolve().parent.parent / "benchmark" / "query-perf-budget.json").read_text())
    for name, cls in CLASSES.items():
        if cls.get("control"):
            assert "f" not in cls, name
            continue
        assert name in budget["classes"], f"{name} has no budget"
        pushed, defeated = render(cls, False, True), render(cls, True, True)
        assert f"FILTER(({cls['f']}) || false)" in defeated, name
        assert "|| false" not in pushed, name
        assert "{f}" not in pushed and "{f}" not in defeated, name
        if cls.get("limit"):
            assert pushed.endswith(f"LIMIT {cls['limit']}"), name
            assert "LIMIT" not in render(cls, False, False), name
    extra = set(budget["classes"]) - set(CLASSES)
    assert not extra, f"budget names unknown classes {extra}"
    print(f"self-test ok: {len(CLASSES)} classes")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    sub = parser.add_subparsers(dest="cmd", required=True)
    g = sub.add_parser("generate")
    g.add_argument("--out", type=Path, required=True)
    g.add_argument("--entities", type=int, default=150_000)
    g.add_argument("--seed", type=int, default=66)
    g.add_argument("--graphs", type=int, default=26)
    sub.add_parser("self-test")
    ld = sub.add_parser("load")
    ld.add_argument("--fixture", type=Path, required=True)
    ld.add_argument("--db", type=Path, required=True)
    ld.add_argument("--quipu", default="quipu")
    for name in ("gate", "smoke"):
        p = sub.add_parser(name)
        p.add_argument("--url", default="http://127.0.0.1:3030")
        p.add_argument("--reps", type=int, default=7)
        p.add_argument("--timeout", type=float, default=30.0)
        p.add_argument("--output", type=Path)
        if name == "gate":
            p.add_argument("--budget", type=Path, required=True)
            p.add_argument("--only", nargs="+")
    args = parser.parse_args()
    if args.cmd == "generate":
        m = generate(args.out, args.entities, args.seed, args.graphs)
        print(json.dumps({k: m[k] for k in ("entities", "triples", "graphs")}))
        return 0
    if args.cmd == "self-test":
        self_test()
        return 0
    if args.cmd == "load":
        started = time.monotonic()
        load(args.fixture, args.db, args.quipu)
        print(f"loaded {args.fixture} into {args.db} in {time.monotonic() - started:.1f}s")
        return 0
    if args.cmd == "gate":
        budget = json.loads(args.budget.read_text())
        missing = [n for n, c in CLASSES.items() if not c.get("control") and n not in budget["classes"]]
        if missing:
            print(f"budget has no entry for {missing}", file=sys.stderr)
            return 2
        report, failures = gate(args.url, budget, args.reps, args.timeout, args.only)
    else:
        report, failures = smoke(args.url, args.reps, args.timeout), []
    text = json.dumps(report, indent=2)
    if args.output:
        args.output.write_text(text + "\n")
    print(text)
    for f in failures:
        print(f"FAIL {f}", file=sys.stderr)
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
