//! Episode ingestion — structured write path for agent-extracted knowledge.
//!
//! Episodes are the primary unit of knowledge ingestion from Gas Town agents.
//! An episode contains a set of nodes (entities) and edges (relationships)
//! extracted from operational events, bead work, or infrastructure observations.
//!
//! This module converts the structured JSON format used by Graphiti/Gas Town
//! into RDF Turtle and writes it through the existing `ingest_rdf` pipeline.

use serde::Deserialize;

use crate::error::{Error, Result};
use crate::rdf::ingest_rdf;
use crate::shacl;
use crate::store::Store;

const BASE_NS: &str = "http://aegis.gastown.local/ontology/";

/// An episode — a unit of knowledge to ingest.
#[derive(Debug, Deserialize)]
pub struct Episode {
    pub name: String,
    #[serde(default)]
    pub episode_body: Option<String>,
    #[serde(default)]
    pub source: Option<String>,
    #[serde(default)]
    pub group_id: Option<String>,
    #[serde(default)]
    pub nodes: Vec<Node>,
    #[serde(default)]
    pub edges: Vec<Edge>,
    /// Optional SHACL shapes (Turtle) to validate generated triples against.
    #[serde(default)]
    pub shapes: Option<String>,
}

/// A node (entity) extracted from an episode.
#[derive(Debug, Deserialize)]
pub struct Node {
    pub name: String,
    #[serde(rename = "type", default)]
    pub node_type: Option<String>,
    #[serde(default)]
    pub description: Option<String>,
    #[serde(default)]
    pub properties: Option<serde_json::Map<String, serde_json::Value>>,
}

/// An edge (relationship) between two nodes.
#[derive(Debug, Deserialize)]
pub struct Edge {
    pub source: String,
    pub target: String,
    pub relation: String,
}

/// Ingest an episode into the store.
///
/// Converts nodes and edges to Turtle and writes via `ingest_rdf`.
/// Returns `(tx_id, triple_count)`.
pub fn ingest_episode(
    store: &mut Store,
    episode: &Episode,
    timestamp: &str,
) -> Result<(i64, usize)> {
    let turtle = episode_to_turtle(episode);

    // SHACL validation gate: if shapes provided, validate before writing.
    if let Some(shapes) = &episode.shapes {
        let feedback = shacl::validate_shapes(shapes, &turtle)?;
        if !feedback.conforms {
            let messages: Vec<String> = feedback
                .results
                .iter()
                .map(|r| {
                    format!(
                        "{}: {} ({})",
                        r.severity,
                        r.message.as_deref().unwrap_or("no message"),
                        r.focus_node
                    )
                })
                .collect();
            return Err(Error::ValidationFailed {
                violations: feedback.violations,
                messages,
            });
        }
    }

    let actor = episode.source.as_deref();
    let source_str = format!("episode:{}", episode.name);

    ingest_rdf(
        store,
        turtle.as_bytes(),
        oxrdfio::RdfFormat::Turtle,
        None,
        timestamp,
        actor,
        Some(&source_str),
    )
}

/// Ingest multiple episodes in sequence, each as its own transaction.
/// Stops on first error.
pub fn ingest_batch(
    store: &mut Store,
    episodes: &[Episode],
    timestamps: &[&str],
) -> Result<Vec<(i64, usize)>> {
    let mut results = Vec::with_capacity(episodes.len());
    for (i, episode) in episodes.iter().enumerate() {
        let ts = timestamps.get(i).copied().unwrap_or("1970-01-01T00:00:00Z");
        results.push(ingest_episode(store, episode, ts)?);
    }
    Ok(results)
}

/// Query all entities generated by a specific episode via prov:wasGeneratedBy.
pub fn episode_provenance(
    store: &Store,
    episode_name: &str,
) -> Result<Vec<(String, Vec<crate::types::Fact>)>> {
    let ep_local = sanitize_iri_local(episode_name);
    let ep_iri = format!("{BASE_NS}episode_{ep_local}");
    let query = format!(
        "SELECT DISTINCT ?s WHERE {{ ?s <http://www.w3.org/ns/prov#wasGeneratedBy> <{ep_iri}> }}"
    );
    let result = crate::sparql::query(store, &query)?;

    let mut entities = Vec::new();
    for row in &result.rows {
        if let Some(crate::types::Value::Ref(id)) = row.get("s") {
            let iri = store.resolve(*id)?;
            let facts = store.entity_facts(*id)?;
            entities.push((iri, facts));
        }
    }
    Ok(entities)
}

// ── Turtle generation ──────────────────────────────────────────

fn episode_to_turtle(episode: &Episode) -> String {
    let mut ttl = String::new();

    // Prefixes.
    ttl.push_str(&format!("@prefix aegis: <{BASE_NS}> .\n"));
    ttl.push_str("@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .\n");
    ttl.push_str("@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .\n");
    ttl.push_str("@prefix prov: <http://www.w3.org/ns/prov#> .\n");
    ttl.push_str("@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n\n");

    let ep_local = sanitize_iri_local(&episode.name);

    // Episode provenance entity.
    ttl.push_str(&format!("aegis:episode_{ep_local} a prov:Activity ;\n"));
    ttl.push_str(&format!(
        "    rdfs:label \"{}\"",
        escape_turtle(&episode.name)
    ));
    if let Some(body) = &episode.episode_body {
        ttl.push_str(&format!(
            " ;\n    rdfs:comment \"{}\"",
            escape_turtle(body)
        ));
    }
    if let Some(source) = &episode.source {
        ttl.push_str(&format!(
            " ;\n    prov:wasAssociatedWith \"{}\"",
            escape_turtle(source)
        ));
    }
    if let Some(gid) = &episode.group_id {
        ttl.push_str(&format!(
            " ;\n    aegis:groupId \"{}\"",
            escape_turtle(gid)
        ));
    }
    ttl.push_str(" .\n\n");

    // Nodes.
    for node in &episode.nodes {
        let local = sanitize_iri_local(&node.name);
        ttl.push_str(&format!("aegis:{local}"));

        if let Some(ntype) = &node.node_type {
            let type_local = sanitize_iri_local(ntype);
            ttl.push_str(&format!(" a aegis:{type_local}"));
        }

        ttl.push_str(&format!(
            " ;\n    rdfs:label \"{}\"",
            escape_turtle(&node.name)
        ));

        if let Some(desc) = &node.description {
            ttl.push_str(&format!(
                " ;\n    rdfs:comment \"{}\"",
                escape_turtle(desc)
            ));
        }

        // Link to episode provenance.
        ttl.push_str(&format!(
            " ;\n    prov:wasGeneratedBy aegis:episode_{ep_local}"
        ));

        // Optional properties as typed literals.
        if let Some(props) = &node.properties {
            for (key, val) in props {
                let pred = sanitize_iri_local(key);
                match val {
                    serde_json::Value::String(s) => {
                        ttl.push_str(&format!(
                            " ;\n    aegis:{pred} \"{}\"",
                            escape_turtle(s)
                        ));
                    }
                    serde_json::Value::Number(n) => {
                        if let Some(i) = n.as_i64() {
                            ttl.push_str(&format!(
                                " ;\n    aegis:{pred} \"{i}\"^^xsd:integer"
                            ));
                        } else if let Some(f) = n.as_f64() {
                            ttl.push_str(&format!(
                                " ;\n    aegis:{pred} \"{f}\"^^xsd:double"
                            ));
                        }
                    }
                    serde_json::Value::Bool(b) => {
                        ttl.push_str(&format!(
                            " ;\n    aegis:{pred} \"{b}\"^^xsd:boolean"
                        ));
                    }
                    _ => {} // skip arrays/objects/null
                }
            }
        }

        ttl.push_str(" .\n\n");
    }

    // Edges.
    for edge in &episode.edges {
        let src = sanitize_iri_local(&edge.source);
        let tgt = sanitize_iri_local(&edge.target);
        let rel = sanitize_iri_local(&edge.relation);
        ttl.push_str(&format!("aegis:{src} aegis:{rel} aegis:{tgt} .\n"));
    }

    ttl
}

/// Sanitize a name into a valid IRI local name.
fn sanitize_iri_local(name: &str) -> String {
    name.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '-' || c == '_' || c == '.' {
                c
            } else {
                '_'
            }
        })
        .collect()
}

/// Escape special characters for Turtle string literals.
fn escape_turtle(s: &str) -> String {
    s.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn parse_episode(json: &str) -> Episode {
        serde_json::from_str(json).unwrap()
    }

    #[test]
    fn deserialize_episode() {
        let ep = parse_episode(r#"{
            "name": "koror-discovery",
            "episode_body": "Discovered koror runs ct-205",
            "source": "crew/mayor",
            "group_id": "aegis-ontology",
            "nodes": [
                {"name": "koror", "type": "ProxmoxNode", "description": "Primary Proxmox node"},
                {"name": "ct-205", "type": "LXCContainer"}
            ],
            "edges": [
                {"source": "koror", "target": "ct-205", "relation": "runs_on"}
            ]
        }"#);

        assert_eq!(ep.name, "koror-discovery");
        assert_eq!(ep.nodes.len(), 2);
        assert_eq!(ep.edges.len(), 1);
        assert_eq!(ep.nodes[0].node_type.as_deref(), Some("ProxmoxNode"));
    }

    #[test]
    fn episode_to_turtle_generates_valid_rdf() {
        let ep = parse_episode(r#"{
            "name": "test-episode",
            "episode_body": "Test body",
            "source": "unit-test",
            "nodes": [
                {"name": "alpha", "type": "ServiceType", "description": "Alpha service"}
            ],
            "edges": []
        }"#);

        let ttl = episode_to_turtle(&ep);

        // Should contain prefixes.
        assert!(ttl.contains("@prefix aegis:"));
        assert!(ttl.contains("@prefix prov:"));

        // Should contain episode entity.
        assert!(ttl.contains("aegis:episode_test-episode a prov:Activity"));
        assert!(ttl.contains("rdfs:label \"test-episode\""));
        assert!(ttl.contains("rdfs:comment \"Test body\""));

        // Should contain node.
        assert!(ttl.contains("aegis:alpha a aegis:ServiceType"));
        assert!(ttl.contains("prov:wasGeneratedBy aegis:episode_test-episode"));
    }

    #[test]
    fn ingest_episode_writes_to_store() {
        let mut store = Store::open_in_memory().unwrap();

        let ep = parse_episode(r#"{
            "name": "infra-scan",
            "episode_body": "Infrastructure scan results",
            "source": "crew/mayor",
            "group_id": "aegis-ontology",
            "nodes": [
                {"name": "koror", "type": "ProxmoxNode", "description": "Proxmox host"},
                {"name": "ct-205", "type": "LXCContainer", "description": "Dolt container"}
            ],
            "edges": [
                {"source": "koror", "target": "ct-205", "relation": "runs"}
            ]
        }"#);

        let (tx_id, count) = ingest_episode(&mut store, &ep, "2026-04-04T12:00:00Z").unwrap();

        assert!(tx_id > 0);
        // Episode (4: type + label + comment + wasAssociatedWith + groupId = 5)
        // + koror (4: type + label + comment + wasGeneratedBy = 4)
        // + ct-205 (4: type + label + comment + wasGeneratedBy = 4)
        // + 1 edge = 14 total
        assert!(count >= 10, "expected at least 10 triples, got {count}");

        // Verify entities are in the store.
        let koror = store
            .lookup("http://aegis.gastown.local/ontology/koror")
            .unwrap();
        assert!(koror.is_some(), "koror entity should exist");

        let ct205 = store
            .lookup("http://aegis.gastown.local/ontology/ct-205")
            .unwrap();
        assert!(ct205.is_some(), "ct-205 entity should exist");

        // Verify the episode provenance entity.
        let ep_ent = store
            .lookup("http://aegis.gastown.local/ontology/episode_infra-scan")
            .unwrap();
        assert!(ep_ent.is_some(), "episode entity should exist");
    }

    #[test]
    fn node_properties_become_triples() {
        let mut store = Store::open_in_memory().unwrap();

        let ep = parse_episode(r#"{
            "name": "prop-test",
            "nodes": [
                {
                    "name": "svc1",
                    "type": "WebService",
                    "properties": {
                        "port": 8080,
                        "hostname": "svc1.svc",
                        "active": true
                    }
                }
            ],
            "edges": []
        }"#);

        let (_, count) = ingest_episode(&mut store, &ep, "2026-04-04T12:00:00Z").unwrap();

        // Episode (2: type + label) + node (type + label + wasGeneratedBy + 3 props = 6) = 8
        assert!(count >= 7, "expected at least 7 triples, got {count}");

        let port_id = store
            .lookup("http://aegis.gastown.local/ontology/port")
            .unwrap();
        assert!(port_id.is_some(), "port predicate should exist");
    }

    #[test]
    fn sanitize_iri_local_handles_special_chars() {
        assert_eq!(sanitize_iri_local("ct-205"), "ct-205");
        assert_eq!(sanitize_iri_local("hello world"), "hello_world");
        assert_eq!(sanitize_iri_local("a/b:c"), "a_b_c");
        assert_eq!(sanitize_iri_local("node.name"), "node.name");
    }

    #[test]
    fn escape_turtle_handles_quotes() {
        assert_eq!(escape_turtle(r#"say "hello""#), r#"say \"hello\""#);
        assert_eq!(escape_turtle("line1\nline2"), "line1\\nline2");
    }

    #[test]
    fn minimal_episode_with_body_only() {
        let mut store = Store::open_in_memory().unwrap();

        let ep = parse_episode(r#"{
            "name": "simple-note",
            "episode_body": "Koror was rebooted at 14:00 UTC"
        }"#);

        let (tx_id, count) = ingest_episode(&mut store, &ep, "2026-04-04T14:00:00Z").unwrap();
        assert!(tx_id > 0);
        // Just the episode entity: type + label + comment = 3
        assert_eq!(count, 3);
    }

    #[test]
    fn shacl_validation_rejects_invalid_episode() {
        let mut store = Store::open_in_memory().unwrap();

        let shapes = concat!(
            "@prefix sh: <http://www.w3.org/ns/shacl#> .\n",
            "@prefix aegis: <http://aegis.gastown.local/ontology/> .\n",
            "aegis:WebServiceShape a sh:NodeShape ;\n",
            "    sh:targetClass aegis:WebService ;\n",
            "    sh:property [ sh:path aegis:port ; sh:minCount 1 ] .\n"
        );

        let ep = Episode {
            name: "bad-service".into(),
            episode_body: None,
            source: None,
            group_id: None,
            nodes: vec![Node {
                name: "broken-svc".into(),
                node_type: Some("WebService".into()),
                description: Some("Missing port".into()),
                properties: None,
            }],
            edges: vec![],
            shapes: Some(shapes.into()),
        };

        let err = ingest_episode(&mut store, &ep, "2026-04-04T12:00:00Z").unwrap_err();
        match err {
            Error::ValidationFailed { violations, messages } => {
                assert!(violations > 0);
                assert!(!messages.is_empty());
            }
            other => panic!("expected ValidationFailed, got: {other}"),
        }

        // Nothing should have been written.
        assert!(store.current_facts().unwrap().is_empty());
    }

    #[test]
    fn shacl_validation_passes_valid_episode() {
        let mut store = Store::open_in_memory().unwrap();

        let shapes = concat!(
            "@prefix sh: <http://www.w3.org/ns/shacl#> .\n",
            "@prefix aegis: <http://aegis.gastown.local/ontology/> .\n",
            "aegis:WebServiceShape a sh:NodeShape ;\n",
            "    sh:targetClass aegis:WebService ;\n",
            "    sh:property [ sh:path aegis:port ; sh:minCount 1 ] .\n"
        );

        let mut props = serde_json::Map::new();
        props.insert("port".into(), serde_json::json!(8080));

        let ep = Episode {
            name: "good-service".into(),
            episode_body: None,
            source: None,
            group_id: None,
            nodes: vec![Node {
                name: "valid-svc".into(),
                node_type: Some("WebService".into()),
                description: None,
                properties: Some(props),
            }],
            edges: vec![],
            shapes: Some(shapes.into()),
        };

        let (tx_id, count) = ingest_episode(&mut store, &ep, "2026-04-04T12:00:00Z").unwrap();
        assert!(tx_id > 0);
        assert!(count > 0);
    }

    #[test]
    fn batch_ingestion() {
        let mut store = Store::open_in_memory().unwrap();

        let episodes: Vec<Episode> = vec![
            parse_episode(r#"{"name": "batch-1", "nodes": [{"name": "a1", "type": "Thing"}], "edges": []}"#),
            parse_episode(r#"{"name": "batch-2", "nodes": [{"name": "b1", "type": "Thing"}], "edges": []}"#),
            parse_episode(r#"{"name": "batch-3", "nodes": [{"name": "c1", "type": "Thing"}], "edges": []}"#),
        ];
        let timestamps = vec!["2026-04-04T12:00:00Z", "2026-04-04T12:01:00Z", "2026-04-04T12:02:00Z"];

        let results = ingest_batch(&mut store, &episodes, &timestamps).unwrap();
        assert_eq!(results.len(), 3);
        assert!(results[0].0 < results[1].0);
        assert!(results[1].0 < results[2].0);
    }

    #[test]
    fn provenance_query() {
        let mut store = Store::open_in_memory().unwrap();

        let ep = parse_episode(r#"{
            "name": "prov-test",
            "nodes": [
                {"name": "server1", "type": "Host"},
                {"name": "server2", "type": "Host"}
            ],
            "edges": []
        }"#);

        ingest_episode(&mut store, &ep, "2026-04-04T12:00:00Z").unwrap();

        let entities = episode_provenance(&store, "prov-test").unwrap();
        let iris: Vec<&str> = entities.iter().map(|(iri, _)| iri.as_str()).collect();
        assert!(iris.contains(&"http://aegis.gastown.local/ontology/server1"));
        assert!(iris.contains(&"http://aegis.gastown.local/ontology/server2"));
    }

    #[test]
    fn batch_stops_on_validation_failure() {
        let mut store = Store::open_in_memory().unwrap();

        let shapes = concat!(
            "@prefix sh: <http://www.w3.org/ns/shacl#> .\n",
            "@prefix aegis: <http://aegis.gastown.local/ontology/> .\n",
            "aegis:S a sh:NodeShape ;\n",
            "    sh:targetClass aegis:Thing ;\n",
            "    sh:property [ sh:path aegis:label ; sh:minCount 1 ] .\n"
        );

        let mut good_props = serde_json::Map::new();
        good_props.insert("label".into(), serde_json::json!("ok"));

        let episodes = vec![
            Episode {
                name: "ok-ep".into(),
                episode_body: None,
                source: None,
                group_id: None,
                nodes: vec![Node {
                    name: "good".into(),
                    node_type: Some("Thing".into()),
                    description: None,
                    properties: Some(good_props),
                }],
                edges: vec![],
                shapes: Some(shapes.into()),
            },
            Episode {
                name: "bad-ep".into(),
                episode_body: None,
                source: None,
                group_id: None,
                nodes: vec![Node {
                    name: "bad".into(),
                    node_type: Some("Thing".into()),
                    description: None,
                    properties: None,
                }],
                edges: vec![],
                shapes: Some(shapes.into()),
            },
        ];
        let timestamps = vec!["2026-04-04T12:00:00Z", "2026-04-04T12:01:00Z"];

        let err = ingest_batch(&mut store, &episodes, &timestamps);
        assert!(err.is_err());

        // First episode should have been ingested before failure.
        let prov = episode_provenance(&store, "ok-ep").unwrap();
        assert_eq!(prov.len(), 1);
    }
}
